/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordeer;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class ComparePan extends javax.swing.JPanel {
    private Image img=null;
    private int Width=0;
    private int Height=0;
    public static int flag=0;
    JFrame frame=null;
    public ComparePan(JFrame frame) {
        try {
            img=ImageIO.read(new File("img\\back.png"));
        } catch (IOException ex) {}
        initComponents();
        this.frame=frame;
        btnSubmit.setFocusPainted(false);btnSubmit.setOpaque(false);btnSubmit.setContentAreaFilled(false);btnSubmit.setBorderPainted(false);
        btnExit.setFocusPainted(false);btnExit.setOpaque(false);btnExit.setContentAreaFilled(false);btnExit.setBorderPainted(false);
        btnClear1.setFocusPainted(false);btnClear1.setOpaque(false);btnClear1.setContentAreaFilled(false);btnClear1.setBorderPainted(false);
        btnClear2.setFocusPainted(false);btnClear2.setOpaque(false);btnClear2.setContentAreaFilled(false);btnClear2.setBorderPainted(false);
    }
    @Override
    public void paintComponent(Graphics g)
    {
        this.Width=this.getSize().width;
        this.Height=this.getSize().height; 
        super.paintComponent(g);
        g.drawImage(img, 0, 0,Width,Height, null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        btnSubmit = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextPane1.setBackground(new java.awt.Color(255, 255, 153));
        jTextPane1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextPane1.setText("public class main {\n         public static void main (String[] args) {\n         }\n}");
        jTextPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jTextPane2.setBackground(new java.awt.Color(255, 255, 153));
        jTextPane2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextPane2.setText("public class main {\n         public static void main (String[] args) {\n         }\n}");
        jTextPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane2KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordeer/submit.png"))); // NOI18N
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordeer/clear.png"))); // NOI18N
        btnClear1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        btnClear2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordeer/clear.png"))); // NOI18N
        btnClear2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordeer/exit.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("ENTER First CODE HERE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("ENTER Second CODE HERE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273)
                .addComponent(btnClear1)
                .addGap(348, 348, 348))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit)
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane2KeyTyped
        String text=jTextPane2.getText();
        if(!(text.contains("public class main {")&&text.contains("public static void main (String[] args) {")))
        {
            JOptionPane.showMessageDialog(null, "YOU CAN't Delete this part of Code", "ERROR", JOptionPane.ERROR_MESSAGE);
            jTextPane2.setText("public class main {\n         public static void main (String[] args) {\n          }\n}");
            jTextPane2.setCaretPosition(jTextPane2.getText().length()-13);
        }
        else if(evt.getKeyChar()=='\n')
        {
            int cou=0;
            for (int i = 0; i < jTextPane2.getCaretPosition(); i++) {
                if(text.charAt(i)=='{')
                {
                    cou++;
                }
                else if(text.charAt(i)=='}')
                {
                    cou--;
                }
            }
            String append="";
            for (int i = 0; i < cou; i++) {
                append+="\t";
            }
            jTextPane2.setText(text.substring(0, text.length()-13)+append+text.substring(text.length()-13, text.length()));
            jTextPane2.setCaretPosition(jTextPane2.getText().length()-13);
        }
    }//GEN-LAST:event_jTextPane2KeyTyped

    private void jTextPane1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane1KeyTyped
        String text=jTextPane1.getText();
        if(!(text.contains("public class main {")&&text.contains("public static void main (String[] args) {")))
        {
            JOptionPane.showMessageDialog(null, "YOU CAN't Delete this part of Code", "ERROR", JOptionPane.ERROR_MESSAGE);
            jTextPane1.setText("public class main {\n         public static void main (String[] args) {\n          }\n}");
            jTextPane1.setCaretPosition(jTextPane1.getText().length()-13);
        }
        else if(evt.getKeyChar()=='\n')
        {
            int cou=0;
            for (int i = 0; i < jTextPane1.getCaretPosition(); i++) {
                if(text.charAt(i)=='{')
                {
                    cou++;
                }
                else if(text.charAt(i)=='}')
                {
                    cou--;
                }
            }
            String append="";
            for (int i = 0; i < cou; i++) {
                append+="\t";
            }
            jTextPane1.setText(text.substring(0, text.length()-13)+append+text.substring(text.length()-13, text.length()));
            jTextPane1.setCaretPosition(jTextPane1.getText().length()-13);
        }
    }//GEN-LAST:event_jTextPane1KeyTyped

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        jTextPane2.setText("public class main {\n         public static void main (String[] args) {\n          }\n}");
        jTextPane2.setCaretPosition(jTextPane2.getText().length()-13);
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        jTextPane1.setText("public class main {\n         public static void main (String[] args) {\n          }\n}");
        jTextPane1.setCaretPosition(jTextPane1.getText().length()-13);
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Are you sure?");  
        if(a==JOptionPane.YES_OPTION){  
            frame.setVisible(false);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            String text1=jTextPane1.getText();
            String text2=jTextPane2.getText();
            JFrame myapp=new JFrame();
            myapp.setExtendedState(JFrame.MAXIMIZED_BOTH);
            myapp.setUndecorated(true);
            Load app=new Load(text1,text2,myapp);
            myapp.add(app);
            myapp.setVisible(true);
            TimeUnit.SECONDS.sleep(1);
            frame.setVisible(false);
            app.start1();
        } catch (InterruptedException ex) {
            Logger.getLogger(SinglePan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
