/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordeer;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class SinglePan extends javax.swing.JPanel {

    /**
     * Creates new form SinglePan
     */
    private Image img=null;
    private int Width=0;
    private int Height=0;
    JFrame frame=null;
    public SinglePan(JFrame frame) {
        try {
            img=ImageIO.read(new File("img\\back.png"));
        } catch (IOException ex) {}
        initComponents();
        this.frame=frame;
        btnSubmit.setFocusPainted(false);btnSubmit.setOpaque(false);btnSubmit.setContentAreaFilled(false);btnSubmit.setBorderPainted(false);
        btnExit.setFocusPainted(false);btnExit.setOpaque(false);btnExit.setContentAreaFilled(false);btnExit.setBorderPainted(false);
        btnClear.setFocusPainted(false);btnClear.setOpaque(false);btnClear.setContentAreaFilled(false);btnClear.setBorderPainted(false);
    }
    @Override
    public void paintComponent(Graphics g)
    {
        this.Width=this.getSize().width;
        this.Height=this.getSize().height; 
        super.paintComponent(g);
        g.drawImage(img, 0, 0,Width,Height, null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jTextPane1.setBackground(new java.awt.Color(255, 255, 153));
        jTextPane1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextPane1.setText("public class main {\n         public static void main (String[] args) {\n         }\n}");
        jTextPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("ENTER YOUR CODE HERE");

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordeer/clear.png"))); // NOI18N
        btnClear.setMnemonic('\u0633');
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordeer/submit.png"))); // NOI18N
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordeer/exit.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(421, 421, 421))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(556, 556, 556))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPane1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane1KeyTyped
        String text=jTextPane1.getText();
        if(!(text.contains("public class main {")&&text.contains("public static void main (String[] args) {")))
        {
            JOptionPane.showMessageDialog(null, "YOU CAN't Delete this part of Code", "ERROR", JOptionPane.ERROR_MESSAGE);
            jTextPane1.setText("public class main {\n         public static void main (String[] args) {\n          }\n}");
            jTextPane1.setCaretPosition(jTextPane1.getText().length()-13);
        }
        else if(evt.getKeyChar()=='\n')
        {
            int cou=0;
            for (int i = 0; i < jTextPane1.getCaretPosition(); i++) {
                if(text.charAt(i)=='{')
                {
                    cou++;
                }
                else if(text.charAt(i)=='}')
                {
                    cou--;
                }
            }
            String append="";
            for (int i = 0; i < cou; i++) {
                append+="\t";
            }
            jTextPane1.setText(text.substring(0, text.length()-13)+append+text.substring(text.length()-13, text.length()));
            jTextPane1.setCaretPosition(jTextPane1.getText().length()-13);
        }
    }//GEN-LAST:event_jTextPane1KeyTyped

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        jTextPane1.setText("public class main {\n         public static void main (String[] args) {\n\n          }\n}");
            jTextPane1.setCaretPosition(jTextPane1.getText().length()-14);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            String text=jTextPane1.getText();
            JFrame myapp=new JFrame();
            myapp.setExtendedState(JFrame.MAXIMIZED_BOTH);
            myapp.setUndecorated(true);
            Load app=new Load(text,myapp);
            myapp.add(app);
            myapp.setVisible(true);
            TimeUnit.SECONDS.sleep(1);
            frame.setVisible(false);
            app.start();
        } catch (InterruptedException ex) {
            Logger.getLogger(SinglePan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Are you sure?");  
        if(a==JOptionPane.YES_OPTION){  
            frame.setVisible(false);
        }
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
